// Tiny interactive demo: no build step, just static assets.
const commitBtn = document.getElementById("commit-btn");
const countEl = document.getElementById("commit-count");
const logEl = document.getElementById("log");
const buildInfo = document.getElementById("build-info");

let count = 0;
const shortSha = () => Math.random().toString(16).slice(2, 9);

commitBtn.addEventListener("click", () => {
  count += 1;
  countEl.textContent = count;
  const li = document.createElement("li");
  const time = new Date().toLocaleTimeString();
  li.textContent = `commit ${shortSha()} — demo change #${count} @ ${time}`;
  logEl.prepend(li);
});

// build.json is generated by the GitHub Actions workflow at deploy time.
fetch("build.json")
  .then((r) => (r.ok ? r.json() : Promise.reject()))
  .then((data) => {
    buildInfo.textContent = `${data.sha?.slice(0, 7) ?? "local"} · ${data.built_at ?? "dev"}`;
  })
  .catch(() => {
    buildInfo.textContent = "local dev (no build metadata)";
  });
